services:
  - type: web
    name: customer-intelligence-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /api/health
    envVars:
      - key: HF_REPO_ID
        value: wilique200-daniel/customer-intelligence-churn-model
      - key: PYTHON_VERSION
        value: 3.11.9
